name: iOS CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    name: iOS App Build
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1.6.0

      - name: Install Dependency
        run: |
          brew install swiftlint
          swiftlint --version

      - name: Build App
        run: |
          xcodebuild -scheme iOS-CICD \
          -sdk iphonesimulator \
          -destination "platform=iOS Simulator,name=iPhone 15" \
          clean build

          
          
          
        
      
    
